import request from '@/utils/request'

export const getUsers = (params) => request.get('/admin/users', { params })
export const getUser = (id) => request.get(`/admin/users/${id}`)
export const updateUser = (id, data) => request.put(`/admin/users/${id}`, data)
export const deleteUser = (id) => request.delete(`/admin/users/${id}`)
export const resetUserBalance = (id, data) => request.post(`/admin/users/${id}/reset-balance`, data)
export const impersonateUser = (id) => request.post(`/admin/users/${id}/impersonate`)

export const getOrders = (params) => request.get('/admin/orders', { params })
export const getOrder = (id) => request.get(`/admin/orders/${id}`)
export const updateOrder = (id, data) => request.put(`/admin/orders/${id}`, data)
export const processOrder = (id, data) => request.post(`/admin/orders/${id}/process`)
export const cancelOrder = (id) => request.post(`/admin/orders/${id}/cancel`)

export const getTickets = (params) => request.get('/admin/tickets', { params })
export const getTicket = (id) => request.get(`/admin/tickets/${id}`)
export const replyTicket = (id, data) => request.post(`/admin/tickets/${id}/reply`, data)
export const closeTicket = (id) => request.post(`/admin/tickets/${id}/close`)

export const getProducts = (params) => request.get('/admin/products', { params })
export const getProduct = (id) => request.get(`/admin/products/${id}`)
export const createProduct = (data) => request.post('/admin/products', data)
export const updateProduct = (id, data) => request.put(`/admin/products/${id}`, data)
export const deleteProduct = (id) => request.delete(`/admin/products/${id}`)
export const getPlans = (productId) => request.get(`/admin/products/${productId}/plans`)
export const createPlan = (productId, data) => request.post(`/admin/products/${productId}/plans`, data)
export const updatePlan = (planId, data) => request.put(`/admin/plans/${planId}`, data)
export const deletePlan = (planId) => request.delete(`/admin/plans/${planId}`)

export const getNodes = (params) => request.get('/admin/nodes', { params })
export const getNode = (id) => request.get(`/admin/nodes/${id}`)
export const createNode = (data) => request.post('/admin/nodes', data)
export const updateNode = (id, data) => request.put(`/admin/nodes/${id}`, data)
export const deleteNode = (id) => request.delete(`/admin/nodes/${id}`)
export const syncNode = (id) => request.post(`/admin/nodes/${id}/sync`)
export const syncNodeImages = (id) => request.post(`/admin/nodes/${id}/sync-images`)
export const getNodeStats = (id) => request.get(`/admin/nodes/${id}/stats`)
export const getNodeVMs = (id) => request.get(`/admin/nodes/${id}/vms`)
export const importVM = (nodeId, data) => request.post(`/admin/nodes/${nodeId}/import-vm`, data)

export const getImages = (params) => request.get('/admin/images', { params })
export const getImage = (id) => request.get(`/admin/images/${id}`)
export const createImage = (data) => request.post('/admin/images', data)
export const updateImage = (id, data) => request.put(`/admin/images/${id}`, data)
export const deleteImage = (id) => request.delete(`/admin/images/${id}`)

export const getConfigs = () => request.get('/admin/configs')
export const updateConfigs = (data) => request.put('/admin/configs', data)

export const getAnnouncements = (params) => request.get('/admin/announcements', { params })
export const getAnnouncement = (id) => request.get(`/admin/announcements/${id}`)
export const createAnnouncement = (data) => request.post('/admin/announcements', data)
export const updateAnnouncement = (id, data) => request.put(`/admin/announcements/${id}`, data)
export const deleteAnnouncement = (id) => request.delete(`/admin/announcements/${id}`)

export const getVouchers = (params) => request.get('/admin/vouchers', { params })
export const createVoucher = (data) => request.post('/admin/vouchers', data)
export const deleteVoucher = (id) => request.delete(`/admin/vouchers/${id}`)

export const getService = (id) => request.get(`/admin/services/${id}`)
export const getServices = (params) => request.get('/admin/services', { params })
export const updateService = (id, data) => request.put(`/admin/services/${id}`, data)
export const deleteService = (id) => request.delete(`/admin/services/${id}`)
export const customCreateService = (data) => request.post('/admin/services/custom-create', data)

export const getAdminTickets = (params) => request.get('/admin/tickets', { params })
export const getAuthRequests = (params) => request.get('/admin/auth-requests', { params })
export const approveAuth = (id) => request.post(`/admin/auth-requests/${id}/approve`)
export const rejectAuth = (id, data) => request.post(`/admin/auth-requests/${id}/reject`, data)

export const getRechargeRecords = (params) => request.get('/admin/recharge', { params })

export const getDashboardStats = () => request.get('/admin/dashboard/stats')
export const getDashboardChart = () => request.get('/admin/dashboard/chart')
